source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'collects.art' do
  pod 'Firebase'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'SDCAlertView', '~> 7.1'
  pod 'AlamofireImage'
  pod 'IQKeyboardManagerSwift'
  pod 'AnimatedGIFImageSerialization', '~> 0.2'
  pod 'SESlideTableViewCell', '~> 0.7'
end
